# Generated by Django 5.1.3 on 2024-11-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('EMPLOYEE', 'EMPLOYEE')], default='EMPLOYEE', max_length=10)),
                ('designation', models.CharField(choices=[('Developer Trainee', 'Developer Trainee'), ('Developer', 'Developer'), ('Senior Developer', 'Senior Developer'), ('Intern-Software Development', 'Intern-Software Development'), ('Intern-Machine Learning', 'Intern-Machine Learning'), ('Junior Developer', 'Junior Developer'), ('Project Coordinator', 'Project Coordinator'), ('Product Manager', 'Product Manager'), ('Machine Learning Engineer', 'Machine Learning Engineer'), ('DevOps Engineer', 'DevOps Engineer'), ('UI/UX Designer', 'UI/UX Designer'), ('Quality Assurance Engineer', 'Quality Assurance Engineer'), ('Lead Frontend Engineer', 'Lead Frontend Engineer'), ('Lead Backend Engineer', 'Lead Backend Engineer'), ('HR Manager', 'HR Manager'), ('IT Specialist', 'IT Specialist'), ('Business Analyst', 'Business Analyst'), ('Sales Manager', 'Sales Manager'), ('Marketing Executive', 'Marketing Executive'), ('CTO', 'CTO'), ('CEO', 'CEO')], default='Developer Trainee', max_length=30)),
                ('is_lead', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('employee_id', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('contact_no', models.IntegerField(unique=True)),
                ('date_of_joining', models.DateField()),
                ('office_location', models.CharField(max_length=25)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
